# Generated by Django 5.2.1 on 2025-05-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Aplicativos, Músicas, Séries', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL amigável (letras minúsculas, números, hífens)', max_length=100, unique=True)),
                ('descricao_breve', models.TextField(blank=True, help_text='Pequena descrição da categoria', null=True)),
                ('cor_card', models.CharField(default='#660099', help_text='Cor em hexadecimal (ex: #660099)', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria de Dica',
                'verbose_name_plural': 'Categorias de Dicas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(help_text='A dica detalhada.')),
                ('link_util', models.URLField(blank=True, help_text='Link externo relevante, se houver.', null=True)),
                ('data_adicionada', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicas', to='ingles_facil.categoriadica')),
            ],
            options={
                'verbose_name': 'Dica',
                'verbose_name_plural': 'Dicas',
                'ordering': ['-data_adicionada'],
            },
        ),
    ]
