# Generated by Django 5.2.1 on 2025-05-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles_facil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloAprendizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de apresentação dos módulos')),
                ('pontos_para_desbloquear', models.PositiveIntegerField(default=0, help_text='Pontos totais necessários para acessar este módulo')),
            ],
            options={
                'verbose_name': 'Módulo de Aprendizado',
                'verbose_name_plural': 'Módulos de Aprendizado',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo_ou_pergunta', models.TextField(help_text='Descrição da tarefa, texto para leitura, pergunta do quiz, link do vídeo, etc.')),
                ('pontos_ao_completar', models.PositiveIntegerField(default=10)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem da tarefa dentro do módulo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='ingles_facil.moduloaprendizado')),
            ],
            options={
                'verbose_name': 'Tarefa de Aprendizado',
                'verbose_name_plural': 'Tarefas de Aprendizado',
                'ordering': ['modulo__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_totais', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoUsuarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_tarefas', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingles_facil.tarefa')),
            ],
            options={
                'verbose_name': 'Progresso do Usuário na Tarefa',
                'verbose_name_plural': 'Progressos dos Usuários nas Tarefas',
                'unique_together': {('usuario', 'tarefa')},
            },
        ),
    ]
