# Generated by Django 5.2.1 on 2025-06-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles_facil', '0003_seed_initial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dica',
            name='logo_recurso',
            field=models.ImageField(blank=True, help_text='Logo do site ou app.', null=True, upload_to='logos_recursos/'),
        ),
        migrations.AddField(
            model_name='dica',
            name='nome_recurso',
            field=models.CharField(blank=True, help_text='Nome do site ou app. Ex: Duolingo', max_length=100, null=True),
        ),
    ]
