# Generated by Django 5.2.1 on 2025-08-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles_facil', '0004_dica_logo_recurso_dica_nome_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dica',
            name='logo_recurso',
            field=models.ImageField(blank=True, help_text='Logo do site ou app.', null=True, upload_to='midia/logos_recursos/'),
        ),
    ]
